# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("common.proto", :syntax => :proto3) do
    add_message "common.Empty" do
    end
    add_message "common.StatusResponse" do
      optional :success, :bool, 1
      optional :message, :string, 2
    end
    add_message "common.Timestamp" do
      optional :seconds, :int64, 1
      optional :nanos, :int32, 2
    end
  end
end

module Common
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("common.Empty").msgclass
  StatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("common.StatusResponse").msgclass
  Timestamp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("common.Timestamp").msgclass
end
