# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto

require 'google/protobuf'
require_relative 'common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("notification.proto", :syntax => :proto3) do
    add_message "notification.OrderNotificationRequest" do
      optional :order_id, :string, 1
      optional :customer_name, :string, 2
      optional :status, :string, 3
      optional :total_amount, :double, 4
    end
    add_message "notification.StockAlertRequest" do
      optional :product_id, :string, 1
      optional :product_name, :string, 2
      optional :current_quantity, :int32, 3
      optional :alert_type, :string, 4
    end
    add_message "notification.Notification" do
      optional :id, :string, 1
      optional :type, :string, 2
      optional :message, :string, 3
      optional :created_at, :string, 4
      optional :sent, :bool, 5
    end
    add_message "notification.GetNotificationsRequest" do
      optional :limit, :int32, 1
      optional :offset, :int32, 2
    end
    add_message "notification.NotificationsResponse" do
      repeated :notifications, :message, 1, "notification.Notification"
      optional :total, :int32, 2
    end
  end
end

module Notification
  OrderNotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notification.OrderNotificationRequest").msgclass
  StockAlertRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notification.StockAlertRequest").msgclass
  Notification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notification.Notification").msgclass
  GetNotificationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notification.GetNotificationsRequest").msgclass
  NotificationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notification.NotificationsResponse").msgclass
end
