# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: notification.proto for package 'notification'

require 'grpc'
require_relative 'notification_pb'
require_relative 'common_pb'

module Notification
  module NotificationService
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'notification.NotificationService'

      rpc :SendOrderNotification, ::Notification::OrderNotificationRequest, ::Common::StatusResponse
      rpc :SendStockAlert, ::Notification::StockAlertRequest, ::Common::StatusResponse
      rpc :GetNotifications, ::Notification::GetNotificationsRequest, ::Notification::NotificationsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
