// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package notification

import (
	reflect "reflect"
)

// OrderNotificationRequest
type OrderNotificationRequest struct {
	OrderId      string  `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerName string  `protobuf:"bytes,2,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	Status       string  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TotalAmount  float64 `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
}

func (x *OrderNotificationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderNotificationRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *OrderNotificationRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderNotificationRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

// StockAlertRequest
type StockAlertRequest struct {
	ProductId       string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName     string `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	CurrentQuantity int32  `protobuf:"varint,3,opt,name=current_quantity,json=currentQuantity,proto3" json:"current_quantity,omitempty"`
	AlertType       string `protobuf:"bytes,4,opt,name=alert_type,json=alertType,proto3" json:"alert_type,omitempty"`
}

func (x *StockAlertRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StockAlertRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *StockAlertRequest) GetCurrentQuantity() int32 {
	if x != nil {
		return x.CurrentQuantity
	}
	return 0
}

func (x *StockAlertRequest) GetAlertType() string {
	if x != nil {
		return x.AlertType
	}
	return ""
}

// Notification
type Notification struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Sent      bool   `protobuf:"varint,5,opt,name=sent,proto3" json:"sent,omitempty"`
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Notification) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

// GetNotificationsRequest
type GetNotificationsRequest struct {
	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *GetNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotificationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// NotificationsResponse
type NotificationsResponse struct {
	Notifications []*Notification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Total         int32           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *NotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *NotificationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// StatusResponse
type StatusResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var _ reflect.Type
