// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// NotificationServiceClient is the client API for NotificationService service.
type NotificationServiceClient interface {
	SendOrderNotification(ctx context.Context, in *OrderNotificationRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	SendStockAlert(ctx context.Context, in *StockAlertRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*NotificationsResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) SendOrderNotification(ctx context.Context, in *OrderNotificationRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/SendOrderNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendStockAlert(ctx context.Context, in *StockAlertRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/SendStockAlert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*NotificationsResponse, error) {
	out := new(NotificationsResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/GetNotifications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
type NotificationServiceServer interface {
	SendOrderNotification(context.Context, *OrderNotificationRequest) (*StatusResponse, error)
	SendStockAlert(context.Context, *StockAlertRequest) (*StatusResponse, error)
	GetNotifications(context.Context, *GetNotificationsRequest) (*NotificationsResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) SendOrderNotification(context.Context, *OrderNotificationRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOrderNotification not implemented")
}
func (UnimplementedNotificationServiceServer) SendStockAlert(context.Context, *StockAlertRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendStockAlert not implemented")
}
func (UnimplementedNotificationServiceServer) GetNotifications(context.Context, *GetNotificationsRequest) (*NotificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "SendOrderNotification", Handler: _NotificationService_SendOrderNotification_Handler},
		{MethodName: "SendStockAlert", Handler: _NotificationService_SendStockAlert_Handler},
		{MethodName: "GetNotifications", Handler: _NotificationService_GetNotifications_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}

func _NotificationService_SendOrderNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendOrderNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/notification.NotificationService/SendOrderNotification"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendOrderNotification(ctx, req.(*OrderNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendStockAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendStockAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/notification.NotificationService/SendStockAlert"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendStockAlert(ctx, req.(*StockAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_GetNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).GetNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/notification.NotificationService/GetNotifications"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).GetNotifications(ctx, req.(*GetNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}
